version: "3.8"

#Docker Networks
networks:
  csproject:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
  api-data:
    name: api-data

  # Workflow
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: api
    ports:
      - 8080:80
    volumes:
      - api-data:/var/www/html
    depends_on:
      - database
    networks:
      - csproject

  database:
    image: mysql:5.7
    container_name: database
    platform: linux/amd64
    command: --init-file /database/init.sql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: csproject_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./database/init.sql:/database/init.sql
    networks:
      - csproject