version: "3.8"

#Docker Networks
networks:
  csproject:
    driver: bridge
    external: true

#Volumes
volumes:
  dbdata:
    driver: local
  users-api-data:
    name: users-api-data

  # Workflow
services:
  users_api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: users_api
    ports:
      - 8080:80
    volumes:
      - users-api-data:/var/www/html
    depends_on:
      - users_database
    networks:
      - csproject

  users_database:
    image: mysql:5.7
    container_name: users_database
    platform: linux/amd64
    command: --init-file /database/init.sql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: users_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./database/init.sql:/database/init.sql
    networks:
      - csproject