version: "3.8"

#Docker Networks
networks:
  csproject:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local

  # Workflow
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: api
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
    depends_on:
      - database
    networks:
      - csproject

  database:
    image: percona:5.7
    container_name: database
    platform: linux/amd64
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: local
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - csproject